exports.Constants = {
  VALIDATION_ERR: 401,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  SERVER_ERR: 500,
};

exports.ENV_VARIABLE = {
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  MONGO_URL: process.env.MONGO_URL,
};
